name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master

      - name: build
        run: |
          PACKAGE_REPO='docker.pkg.github.com'
          REPO_OWNER=`echo ${GITHUB_REPOSITORY} | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]'`
          IMAGE_NAME=`echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]'`
          IMAGE_TAG=`echo "${GITHUB_REF}" | cut -d'/' -f3`
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $PACKAGE_REPO -u $REPO_OWNER --password-stdin
          docker build -t $PACKAGE_REPO/$IMAGE_NAME/$IMAGE_TAG --build-arg GIT_COMMIT=${GITHUB_SHA} .
          docker push $PACKAGE_REPO/$IMAGE_NAME/$IMAGE_TAG
