name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master

      - name: build
        uses: ./.github/actions/go
        with:
          args: go build

      - name: fmt
        uses: cedrickring/golang-action@1.3.0
        with:
          args: test -z "`go fmt`"
        env:
          GO111MODULE: "on"

      # - name: pre-fmt
      #   uses: ./.github/actions/go
      #   with:
      #     args: go fmt
      #
      # - name: fmt
      #   uses: ./.github/actions/go
      #   with:
      #     # This fails because go is downloading modules again before running
      #     # `go fmt`. `test -z` is checking for output and because downloading
      #     # modules produces output, causes test to return a non-zero exit code.
      #     args: test -z "`go fmt`"

      - name: vet
        uses: ./.github/actions/go
        with:
          args: go vet

      - name: test
        uses: ./.github/actions/go
        with:
          args: go test
