name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: fmt
        uses: cedrickring/golang-action@1.3.0
        with:
          args: test -z "`go fmt`"
        env:
          GO111MODULE: "on"

      - name: vet
        uses: cedrickring/golang-action@1.3.0
        with:
          args: go vet
        env:
          GO111MODULE: "on"

      - name: test
        uses: cedrickring/golang-action@1.3.0
        with:
          args: go test
        env:
          GO111MODULE: "on"
